config {
    type: "operations",
    schema: "Views",
    hasOutput: true, 
    tags: ["daily"]
}
CREATE OR REPLACE MATERIALIZED VIEW ${self()}
OPTIONS (
    max_staleness = INTERVAL "4:0:0" HOUR TO SECOND
)
AS (
  SELECT
    FundName,
    FundCode,
    NOT STARTS_WITH(FundName, "1") AS IsExtraordinary,
    DATE_TRUNC(GiftDate, WEEK) as GiftWeek,
    SUM(ROUND(Amount, 2)) as Total
FROM
  ${ref("contributions_table")}
GROUP BY
  FundName,
  FundCode,
  IsExtraordinary,
  GiftWeek
);
